### ISSUE TITLE
[Spigot] NullPointerExceptions with Spigot

### ISSUE THREAD

**Issue by darkspirit510** [NerdsWBNerds/EasyWarp#11]
Hi,

i'm not sure if this is a bug of Spigot or EasyWarp, but i'll post it here first. I am using v3.3 and get NullPointerExceptions in my logs. It doesn't cause any crashes but it's annoying... :-)

`[11:27:01] [Server thread/WARN]: [EasyWarp] Task #338 for EasyWarp v3.3 generated an exception
java.lang.NullPointerException
	at org.bukkit.Location.getChunk(Location.java:78) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at com.collinsrichard.easywarp.Helper.warp(Helper.java:73) ~[?:?]
	at com.collinsrichard.easywarp.objects.WarpTimer.run(WarpTimer.java:22) ~[?:?]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot-1.8.8.jar:git-Spigot-e4d4710-e1ebe52]
`

Greetings

**Comment by NerdsWBNerds** [comment]
Fixed in 3.4 (hopefully)
http://dev.bukkit.org/bukkit-plugins/easy-warp/files/20-easy-warp-v3-4/
